customhost = "mydatabase.cuujn9r4krml.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "mydatabase"
custombucket = "my-project.2-bucket"
customregion = "us-east-1"
